// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using proyetoef;

#nullable disable

namespace Proyecto_Entity_F.Migrations
{
    [DbContext(typeof(TareasContext))]
    [Migration("20240821213254_InitialData")]
    partial class InitialData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ProjectoEF.Modelos.Categoria", b =>
                {
                    b.Property<Guid>("CategoriaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Descripcion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<int>("Peso")
                        .HasColumnType("int");

                    b.HasKey("CategoriaId");

                    b.ToTable("Categoria", (string)null);

                    b.HasData(
                        new
                        {
                            CategoriaId = new Guid("df4de29b-8dc1-48bc-93bb-36aabebc879d"),
                            Nombre = "Actividades pendientes",
                            Peso = 20
                        },
                        new
                        {
                            CategoriaId = new Guid("df4de29b-8dc1-48bc-93bb-36aabebc8702"),
                            Nombre = "Actividades Realizadas",
                            Peso = 29
                        });
                });

            modelBuilder.Entity("ProjectoEF.Modelos.Tarea", b =>
                {
                    b.Property<Guid>("TareaID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CategoriaId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Descripcion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<int>("PrioridadTarea")
                        .HasColumnType("int");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.HasKey("TareaID");

                    b.HasIndex("CategoriaId");

                    b.ToTable("Tarea", (string)null);

                    b.HasData(
                        new
                        {
                            TareaID = new Guid("df4de29b-8dc1-48bc-93bb-36aabebc8710"),
                            CategoriaId = new Guid("df4de29b-8dc1-48bc-93bb-36aabebc879d"),
                            FechaCreacion = new DateTime(2024, 8, 21, 16, 32, 52, 661, DateTimeKind.Local).AddTicks(4750),
                            PrioridadTarea = 1,
                            Titulo = "Pago de servicio publicos"
                        },
                        new
                        {
                            TareaID = new Guid("df4de29b-8dc1-48bc-93bb-36aabebc8711"),
                            CategoriaId = new Guid("df4de29b-8dc1-48bc-93bb-36aabebc8702"),
                            FechaCreacion = new DateTime(2024, 8, 21, 16, 32, 52, 661, DateTimeKind.Local).AddTicks(4766),
                            PrioridadTarea = 2,
                            Titulo = "Compra del Mercado"
                        });
                });

            modelBuilder.Entity("ProjectoEF.Modelos.Tarea", b =>
                {
                    b.HasOne("ProjectoEF.Modelos.Categoria", "Categoria")
                        .WithMany("Tareas")
                        .HasForeignKey("CategoriaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Categoria");
                });

            modelBuilder.Entity("ProjectoEF.Modelos.Categoria", b =>
                {
                    b.Navigation("Tareas");
                });
#pragma warning restore 612, 618
        }
    }
}
